// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages_robocup_ssl_wrapper_micro.proto

package sslproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SSL_Micro_WrapperPacket struct {
	Detection            *SSL_Micro_DetectionFrame `protobuf:"bytes,1,opt,name=detection" json:"detection,omitempty"`
	Geometry             *SSL_Micro_GeometryData   `protobuf:"bytes,2,opt,name=geometry" json:"geometry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *SSL_Micro_WrapperPacket) Reset()         { *m = SSL_Micro_WrapperPacket{} }
func (m *SSL_Micro_WrapperPacket) String() string { return proto.CompactTextString(m) }
func (*SSL_Micro_WrapperPacket) ProtoMessage()    {}
func (*SSL_Micro_WrapperPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_robocup_ssl_wrapper_micro_5aaa37d9acdd184d, []int{0}
}
func (m *SSL_Micro_WrapperPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSL_Micro_WrapperPacket.Unmarshal(m, b)
}
func (m *SSL_Micro_WrapperPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSL_Micro_WrapperPacket.Marshal(b, m, deterministic)
}
func (dst *SSL_Micro_WrapperPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSL_Micro_WrapperPacket.Merge(dst, src)
}
func (m *SSL_Micro_WrapperPacket) XXX_Size() int {
	return xxx_messageInfo_SSL_Micro_WrapperPacket.Size(m)
}
func (m *SSL_Micro_WrapperPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_SSL_Micro_WrapperPacket.DiscardUnknown(m)
}

var xxx_messageInfo_SSL_Micro_WrapperPacket proto.InternalMessageInfo

func (m *SSL_Micro_WrapperPacket) GetDetection() *SSL_Micro_DetectionFrame {
	if m != nil {
		return m.Detection
	}
	return nil
}

func (m *SSL_Micro_WrapperPacket) GetGeometry() *SSL_Micro_GeometryData {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func init() {
	proto.RegisterType((*SSL_Micro_WrapperPacket)(nil), "SSL_Micro_WrapperPacket")
}

func init() {
	proto.RegisterFile("messages_robocup_ssl_wrapper_micro.proto", fileDescriptor_messages_robocup_ssl_wrapper_micro_5aaa37d9acdd184d)
}

var fileDescriptor_messages_robocup_ssl_wrapper_micro_5aaa37d9acdd184d = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xc8, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0x8e, 0x2f, 0xca, 0x4f, 0xca, 0x4f, 0x2e, 0x2d, 0x88, 0x2f, 0x2e, 0xce,
	0x89, 0x2f, 0x2f, 0x4a, 0x2c, 0x28, 0x48, 0x2d, 0x8a, 0xcf, 0xcd, 0x4c, 0x2e, 0xca, 0xd7, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x97, 0xd2, 0xc2, 0xaa, 0x32, 0x25, 0xb5, 0x24, 0x35, 0xb9, 0x24, 0x33,
	0x3f, 0x0f, 0x45, 0xad, 0x26, 0x56, 0xb5, 0xe9, 0xa9, 0xf9, 0xb9, 0xa9, 0x25, 0x45, 0x95, 0xc8,
	0x4a, 0x95, 0xda, 0x19, 0xb9, 0xc4, 0x83, 0x83, 0x7d, 0xe2, 0x7d, 0x41, 0x62, 0xf1, 0xe1, 0x10,
	0x8b, 0x03, 0x12, 0x93, 0xb3, 0x53, 0x4b, 0x84, 0xcc, 0xb9, 0x38, 0xe1, 0xe6, 0x4b, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x1b, 0x49, 0xea, 0x21, 0x14, 0xbb, 0xc0, 0xe4, 0xdc, 0x8a, 0x12, 0x73, 0x53,
	0x83, 0x10, 0x6a, 0x85, 0x8c, 0xb9, 0x38, 0x60, 0x96, 0x49, 0x30, 0x81, 0xf5, 0x89, 0x23, 0xe9,
	0x73, 0x87, 0x4a, 0xb9, 0x24, 0x96, 0x24, 0x06, 0xc1, 0x15, 0x02, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xd3, 0x00, 0x2f, 0x0f, 0x0b, 0x01, 0x00, 0x00,
}
