// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssl_match_stats.proto

package sslproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TeamColor int32

const (
	TeamColor_TEAM_UNKNOWN TeamColor = 0
	TeamColor_TEAM_YELLOW  TeamColor = 1
	TeamColor_TEAM_BLUE    TeamColor = 2
)

var TeamColor_name = map[int32]string{
	0: "TEAM_UNKNOWN",
	1: "TEAM_YELLOW",
	2: "TEAM_BLUE",
}

var TeamColor_value = map[string]int32{
	"TEAM_UNKNOWN": 0,
	"TEAM_YELLOW":  1,
	"TEAM_BLUE":    2,
}

func (x TeamColor) String() string {
	return proto.EnumName(TeamColor_name, int32(x))
}

func (TeamColor) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_21b017991eb90546, []int{0}
}

type CommandType int32

const (
	CommandType_COMMAND_UNKNOWN         CommandType = 0
	CommandType_COMMAND_HALT            CommandType = 1
	CommandType_COMMAND_STOP            CommandType = 2
	CommandType_COMMAND_NORMAL_START    CommandType = 3
	CommandType_COMMAND_FORCE_START     CommandType = 4
	CommandType_COMMAND_PREPARE_KICKOFF CommandType = 5
	CommandType_COMMAND_PREPARE_PENALTY CommandType = 6
	CommandType_COMMAND_DIRECT_FREE     CommandType = 7
	CommandType_COMMAND_INDIRECT_FREE   CommandType = 8
	CommandType_COMMAND_TIMEOUT         CommandType = 9
	CommandType_COMMAND_BALL_PLACEMENT  CommandType = 10
)

var CommandType_name = map[int32]string{
	0:  "COMMAND_UNKNOWN",
	1:  "COMMAND_HALT",
	2:  "COMMAND_STOP",
	3:  "COMMAND_NORMAL_START",
	4:  "COMMAND_FORCE_START",
	5:  "COMMAND_PREPARE_KICKOFF",
	6:  "COMMAND_PREPARE_PENALTY",
	7:  "COMMAND_DIRECT_FREE",
	8:  "COMMAND_INDIRECT_FREE",
	9:  "COMMAND_TIMEOUT",
	10: "COMMAND_BALL_PLACEMENT",
}

var CommandType_value = map[string]int32{
	"COMMAND_UNKNOWN":         0,
	"COMMAND_HALT":            1,
	"COMMAND_STOP":            2,
	"COMMAND_NORMAL_START":    3,
	"COMMAND_FORCE_START":     4,
	"COMMAND_PREPARE_KICKOFF": 5,
	"COMMAND_PREPARE_PENALTY": 6,
	"COMMAND_DIRECT_FREE":     7,
	"COMMAND_INDIRECT_FREE":   8,
	"COMMAND_TIMEOUT":         9,
	"COMMAND_BALL_PLACEMENT":  10,
}

func (x CommandType) String() string {
	return proto.EnumName(CommandType_name, int32(x))
}

func (CommandType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_21b017991eb90546, []int{1}
}

type GamePhaseType int32

const (
	GamePhaseType_PHASE_UNKNOWN         GamePhaseType = 0
	GamePhaseType_PHASE_HALT            GamePhaseType = 1
	GamePhaseType_PHASE_STOP            GamePhaseType = 2
	GamePhaseType_PHASE_RUNNING         GamePhaseType = 3
	GamePhaseType_PHASE_TIMEOUT         GamePhaseType = 4
	GamePhaseType_PHASE_BREAK           GamePhaseType = 5
	GamePhaseType_PHASE_POST_GAME       GamePhaseType = 6
	GamePhaseType_PHASE_PREPARE_KICKOFF GamePhaseType = 7
	GamePhaseType_PHASE_PREPARE_PENALTY GamePhaseType = 8
	GamePhaseType_PHASE_DIRECT_FREE     GamePhaseType = 9
	GamePhaseType_PHASE_INDIRECT_FREE   GamePhaseType = 10
	GamePhaseType_PHASE_BALL_PLACEMENT  GamePhaseType = 11
)

var GamePhaseType_name = map[int32]string{
	0:  "PHASE_UNKNOWN",
	1:  "PHASE_HALT",
	2:  "PHASE_STOP",
	3:  "PHASE_RUNNING",
	4:  "PHASE_TIMEOUT",
	5:  "PHASE_BREAK",
	6:  "PHASE_POST_GAME",
	7:  "PHASE_PREPARE_KICKOFF",
	8:  "PHASE_PREPARE_PENALTY",
	9:  "PHASE_DIRECT_FREE",
	10: "PHASE_INDIRECT_FREE",
	11: "PHASE_BALL_PLACEMENT",
}

var GamePhaseType_value = map[string]int32{
	"PHASE_UNKNOWN":         0,
	"PHASE_HALT":            1,
	"PHASE_STOP":            2,
	"PHASE_RUNNING":         3,
	"PHASE_TIMEOUT":         4,
	"PHASE_BREAK":           5,
	"PHASE_POST_GAME":       6,
	"PHASE_PREPARE_KICKOFF": 7,
	"PHASE_PREPARE_PENALTY": 8,
	"PHASE_DIRECT_FREE":     9,
	"PHASE_INDIRECT_FREE":   10,
	"PHASE_BALL_PLACEMENT":  11,
}

func (x GamePhaseType) String() string {
	return proto.EnumName(GamePhaseType_name, int32(x))
}

func (GamePhaseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_21b017991eb90546, []int{2}
}

type Command struct {
	Type                 CommandType `protobuf:"varint,1,opt,name=type,proto3,enum=CommandType" json:"type,omitempty"`
	ForTeam              TeamColor   `protobuf:"varint,2,opt,name=for_team,json=forTeam,proto3,enum=TeamColor" json:"for_team,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_21b017991eb90546, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetType() CommandType {
	if m != nil {
		return m.Type
	}
	return CommandType_COMMAND_UNKNOWN
}

func (m *Command) GetForTeam() TeamColor {
	if m != nil {
		return m.ForTeam
	}
	return TeamColor_TEAM_UNKNOWN
}

type GamePhase struct {
	StartTime            uint64        `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              uint64        `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Duration             uint32        `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Type                 GamePhaseType `protobuf:"varint,4,opt,name=type,proto3,enum=GamePhaseType" json:"type,omitempty"`
	CommandEntry         *Command      `protobuf:"bytes,5,opt,name=command_entry,json=commandEntry,proto3" json:"command_entry,omitempty"`
	CommandExit          *Command      `protobuf:"bytes,6,opt,name=command_exit,json=commandExit,proto3" json:"command_exit,omitempty"`
	ForTeam              TeamColor     `protobuf:"varint,7,opt,name=for_team,json=forTeam,proto3,enum=TeamColor" json:"for_team,omitempty"`
	GameEventsEntry      []*GameEvent  `protobuf:"bytes,8,rep,name=game_events_entry,json=gameEventsEntry,proto3" json:"game_events_entry,omitempty"`
	GameEventsExit       []*GameEvent  `protobuf:"bytes,9,rep,name=game_events_exit,json=gameEventsExit,proto3" json:"game_events_exit,omitempty"`
	NextCommandProposed  *Command      `protobuf:"bytes,10,opt,name=next_command_proposed,json=nextCommandProposed,proto3" json:"next_command_proposed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GamePhase) Reset()         { *m = GamePhase{} }
func (m *GamePhase) String() string { return proto.CompactTextString(m) }
func (*GamePhase) ProtoMessage()    {}
func (*GamePhase) Descriptor() ([]byte, []int) {
	return fileDescriptor_21b017991eb90546, []int{1}
}

func (m *GamePhase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamePhase.Unmarshal(m, b)
}
func (m *GamePhase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamePhase.Marshal(b, m, deterministic)
}
func (m *GamePhase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamePhase.Merge(m, src)
}
func (m *GamePhase) XXX_Size() int {
	return xxx_messageInfo_GamePhase.Size(m)
}
func (m *GamePhase) XXX_DiscardUnknown() {
	xxx_messageInfo_GamePhase.DiscardUnknown(m)
}

var xxx_messageInfo_GamePhase proto.InternalMessageInfo

func (m *GamePhase) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *GamePhase) GetEndTime() uint64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *GamePhase) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *GamePhase) GetType() GamePhaseType {
	if m != nil {
		return m.Type
	}
	return GamePhaseType_PHASE_UNKNOWN
}

func (m *GamePhase) GetCommandEntry() *Command {
	if m != nil {
		return m.CommandEntry
	}
	return nil
}

func (m *GamePhase) GetCommandExit() *Command {
	if m != nil {
		return m.CommandExit
	}
	return nil
}

func (m *GamePhase) GetForTeam() TeamColor {
	if m != nil {
		return m.ForTeam
	}
	return TeamColor_TEAM_UNKNOWN
}

func (m *GamePhase) GetGameEventsEntry() []*GameEvent {
	if m != nil {
		return m.GameEventsEntry
	}
	return nil
}

func (m *GamePhase) GetGameEventsExit() []*GameEvent {
	if m != nil {
		return m.GameEventsExit
	}
	return nil
}

func (m *GamePhase) GetNextCommandProposed() *Command {
	if m != nil {
		return m.NextCommandProposed
	}
	return nil
}

type TeamStats struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Goals                uint32   `protobuf:"varint,2,opt,name=goals,proto3" json:"goals,omitempty"`
	Fouls                uint32   `protobuf:"varint,3,opt,name=fouls,proto3" json:"fouls,omitempty"`
	YellowCards          uint32   `protobuf:"varint,4,opt,name=yellow_cards,json=yellowCards,proto3" json:"yellow_cards,omitempty"`
	RedCards             uint32   `protobuf:"varint,5,opt,name=red_cards,json=redCards,proto3" json:"red_cards,omitempty"`
	PenaltyShotsTotal    uint32   `protobuf:"varint,6,opt,name=penalty_shots_total,json=penaltyShotsTotal,proto3" json:"penalty_shots_total,omitempty"`
	PenaltyShotsSuccess  uint32   `protobuf:"varint,7,opt,name=penalty_shots_success,json=penaltyShotsSuccess,proto3" json:"penalty_shots_success,omitempty"`
	TimeoutTimes         []uint32 `protobuf:"varint,9,rep,packed,name=timeout_times,json=timeoutTimes,proto3" json:"timeout_times,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamStats) Reset()         { *m = TeamStats{} }
func (m *TeamStats) String() string { return proto.CompactTextString(m) }
func (*TeamStats) ProtoMessage()    {}
func (*TeamStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_21b017991eb90546, []int{2}
}

func (m *TeamStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamStats.Unmarshal(m, b)
}
func (m *TeamStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamStats.Marshal(b, m, deterministic)
}
func (m *TeamStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamStats.Merge(m, src)
}
func (m *TeamStats) XXX_Size() int {
	return xxx_messageInfo_TeamStats.Size(m)
}
func (m *TeamStats) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamStats.DiscardUnknown(m)
}

var xxx_messageInfo_TeamStats proto.InternalMessageInfo

func (m *TeamStats) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TeamStats) GetGoals() uint32 {
	if m != nil {
		return m.Goals
	}
	return 0
}

func (m *TeamStats) GetFouls() uint32 {
	if m != nil {
		return m.Fouls
	}
	return 0
}

func (m *TeamStats) GetYellowCards() uint32 {
	if m != nil {
		return m.YellowCards
	}
	return 0
}

func (m *TeamStats) GetRedCards() uint32 {
	if m != nil {
		return m.RedCards
	}
	return 0
}

func (m *TeamStats) GetPenaltyShotsTotal() uint32 {
	if m != nil {
		return m.PenaltyShotsTotal
	}
	return 0
}

func (m *TeamStats) GetPenaltyShotsSuccess() uint32 {
	if m != nil {
		return m.PenaltyShotsSuccess
	}
	return 0
}

func (m *TeamStats) GetTimeoutTimes() []uint32 {
	if m != nil {
		return m.TimeoutTimes
	}
	return nil
}

type MatchStats struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GamePhases           []*GamePhase       `protobuf:"bytes,4,rep,name=game_phases,json=gamePhases,proto3" json:"game_phases,omitempty"`
	MatchDuration        uint32             `protobuf:"varint,5,opt,name=match_duration,json=matchDuration,proto3" json:"match_duration,omitempty"`
	TimePerGamePhase     map[string]uint32  `protobuf:"bytes,6,rep,name=time_per_game_phase,json=timePerGamePhase,proto3" json:"time_per_game_phase,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	RelTimePerGamePhase  map[string]float32 `protobuf:"bytes,7,rep,name=rel_time_per_game_phase,json=relTimePerGamePhase,proto3" json:"rel_time_per_game_phase,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	TeamStatsYellow      *TeamStats         `protobuf:"bytes,8,opt,name=team_stats_yellow,json=teamStatsYellow,proto3" json:"team_stats_yellow,omitempty"`
	TeamStatsBlue        *TeamStats         `protobuf:"bytes,9,opt,name=team_stats_blue,json=teamStatsBlue,proto3" json:"team_stats_blue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MatchStats) Reset()         { *m = MatchStats{} }
func (m *MatchStats) String() string { return proto.CompactTextString(m) }
func (*MatchStats) ProtoMessage()    {}
func (*MatchStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_21b017991eb90546, []int{3}
}

func (m *MatchStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchStats.Unmarshal(m, b)
}
func (m *MatchStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchStats.Marshal(b, m, deterministic)
}
func (m *MatchStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchStats.Merge(m, src)
}
func (m *MatchStats) XXX_Size() int {
	return xxx_messageInfo_MatchStats.Size(m)
}
func (m *MatchStats) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchStats.DiscardUnknown(m)
}

var xxx_messageInfo_MatchStats proto.InternalMessageInfo

func (m *MatchStats) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MatchStats) GetGamePhases() []*GamePhase {
	if m != nil {
		return m.GamePhases
	}
	return nil
}

func (m *MatchStats) GetMatchDuration() uint32 {
	if m != nil {
		return m.MatchDuration
	}
	return 0
}

func (m *MatchStats) GetTimePerGamePhase() map[string]uint32 {
	if m != nil {
		return m.TimePerGamePhase
	}
	return nil
}

func (m *MatchStats) GetRelTimePerGamePhase() map[string]float32 {
	if m != nil {
		return m.RelTimePerGamePhase
	}
	return nil
}

func (m *MatchStats) GetTeamStatsYellow() *TeamStats {
	if m != nil {
		return m.TeamStatsYellow
	}
	return nil
}

func (m *MatchStats) GetTeamStatsBlue() *TeamStats {
	if m != nil {
		return m.TeamStatsBlue
	}
	return nil
}

func init() {
	proto.RegisterEnum("TeamColor", TeamColor_name, TeamColor_value)
	proto.RegisterEnum("CommandType", CommandType_name, CommandType_value)
	proto.RegisterEnum("GamePhaseType", GamePhaseType_name, GamePhaseType_value)
	proto.RegisterType((*Command)(nil), "Command")
	proto.RegisterType((*GamePhase)(nil), "GamePhase")
	proto.RegisterType((*TeamStats)(nil), "TeamStats")
	proto.RegisterType((*MatchStats)(nil), "MatchStats")
	proto.RegisterMapType((map[string]float32)(nil), "MatchStats.RelTimePerGamePhaseEntry")
	proto.RegisterMapType((map[string]uint32)(nil), "MatchStats.TimePerGamePhaseEntry")
}

func init() { proto.RegisterFile("ssl_match_stats.proto", fileDescriptor_21b017991eb90546) }

var fileDescriptor_21b017991eb90546 = []byte{
	// 954 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0x5d, 0x6f, 0xe2, 0x46,
	0x14, 0x2d, 0xdf, 0xf8, 0x82, 0xc1, 0x19, 0x96, 0xc6, 0x61, 0x55, 0x89, 0xa5, 0x5d, 0x29, 0xca,
	0xaa, 0xa8, 0xa5, 0x55, 0xd5, 0x56, 0xed, 0x83, 0x43, 0x4c, 0x16, 0x05, 0x8c, 0x35, 0x38, 0x5a,
	0xa5, 0x2f, 0x23, 0x2f, 0x4c, 0x12, 0x54, 0x83, 0x91, 0x67, 0xd8, 0x86, 0x3f, 0xd1, 0xa7, 0x3e,
	0x54, 0xea, 0xdf, 0xe8, 0x0f, 0xac, 0x66, 0xc6, 0x06, 0x93, 0x0f, 0xf5, 0x6d, 0xe6, 0x9c, 0x7b,
	0x2f, 0xe7, 0x9e, 0x7b, 0xc7, 0x40, 0x93, 0xb1, 0x80, 0x2c, 0x7d, 0x3e, 0xbb, 0x27, 0x8c, 0xfb,
	0x9c, 0x75, 0xd7, 0x51, 0xc8, 0xc3, 0xd6, 0x89, 0x80, 0xef, 0xfc, 0x25, 0x25, 0xf4, 0x13, 0x5d,
	0x71, 0xd2, 0xfb, 0xe6, 0xdb, 0x9f, 0x14, 0xd5, 0xc1, 0x50, 0xea, 0x87, 0xcb, 0xa5, 0xbf, 0x9a,
	0xa3, 0x36, 0xe4, 0xf9, 0x76, 0x4d, 0xcd, 0x4c, 0x3b, 0x73, 0x5a, 0xeb, 0x55, 0xbb, 0x31, 0xee,
	0x6d, 0xd7, 0x14, 0x4b, 0x06, 0xbd, 0x85, 0xf2, 0x6d, 0x18, 0x11, 0x4e, 0xfd, 0xa5, 0x99, 0x95,
	0x51, 0xd0, 0xf5, 0xa8, 0xbf, 0xec, 0x87, 0x41, 0x18, 0xe1, 0xd2, 0x6d, 0x18, 0x89, 0x5b, 0xe7,
	0xdf, 0x1c, 0x68, 0x97, 0xfe, 0x92, 0xba, 0xf7, 0x3e, 0xa3, 0xe8, 0x0b, 0x00, 0xc6, 0xfd, 0x88,
	0x13, 0xbe, 0x58, 0xaa, 0xe2, 0x79, 0xac, 0x49, 0xc4, 0x5b, 0x2c, 0x29, 0x3a, 0x81, 0x32, 0x5d,
	0xcd, 0x15, 0x99, 0x95, 0x64, 0x89, 0xae, 0xe6, 0x92, 0x6a, 0x41, 0x79, 0xbe, 0x89, 0x7c, 0xbe,
	0x08, 0x57, 0x66, 0xae, 0x9d, 0x39, 0xd5, 0xf1, 0xee, 0x8e, 0x3a, 0xb1, 0xd8, 0xbc, 0x94, 0x51,
	0xeb, 0xee, 0x7e, 0x2f, 0x25, 0xf7, 0x6b, 0xd0, 0x67, 0xaa, 0x07, 0x42, 0x57, 0x3c, 0xda, 0x9a,
	0x85, 0x76, 0xe6, 0xb4, 0xd2, 0x2b, 0x27, 0x9d, 0xe1, 0x6a, 0x4c, 0xdb, 0x82, 0x45, 0xef, 0xa0,
	0xba, 0x0b, 0x7f, 0x58, 0x70, 0xb3, 0xf8, 0x28, 0xba, 0x92, 0x44, 0x3f, 0x2c, 0xf8, 0x81, 0x15,
	0xa5, 0x17, 0xad, 0x40, 0x3f, 0xc0, 0xd1, 0xde, 0x77, 0x16, 0xcb, 0x28, 0xb7, 0x73, 0xa7, 0x95,
	0x1e, 0x48, 0xcd, 0xb6, 0x20, 0x70, 0xfd, 0x2e, 0x39, 0x32, 0xa5, 0xe5, 0x7b, 0x30, 0x0e, 0xf2,
	0x84, 0x1e, 0xed, 0x49, 0x5a, 0x2d, 0x95, 0x26, 0x44, 0xfd, 0x02, 0xcd, 0x15, 0x7d, 0xe0, 0x24,
	0x69, 0x63, 0x1d, 0x85, 0xeb, 0x90, 0xd1, 0xb9, 0x09, 0x8f, 0x5a, 0x69, 0x88, 0xb0, 0xf8, 0xe2,
	0xc6, 0x41, 0x9d, 0xbf, 0xb2, 0xa0, 0x09, 0xd1, 0x53, 0xb1, 0x39, 0x08, 0x41, 0x7e, 0xe5, 0xc7,
	0x03, 0xd3, 0xb0, 0x3c, 0xa3, 0x57, 0x50, 0xb8, 0x0b, 0xfd, 0x80, 0xc9, 0x41, 0xe9, 0x58, 0x5d,
	0x04, 0x7a, 0x1b, 0x6e, 0x02, 0x16, 0xcf, 0x48, 0x5d, 0xd0, 0x1b, 0xa8, 0x6e, 0x69, 0x10, 0x84,
	0x7f, 0x90, 0x99, 0x1f, 0xcd, 0x99, 0x1c, 0x94, 0x8e, 0x2b, 0x0a, 0xeb, 0x0b, 0x08, 0xbd, 0x06,
	0x2d, 0xa2, 0xf3, 0x98, 0x2f, 0xa8, 0x01, 0x47, 0x74, 0xae, 0xc8, 0x2e, 0x34, 0xd6, 0x74, 0xe5,
	0x07, 0x7c, 0x4b, 0xd8, 0x7d, 0xc8, 0x19, 0xe1, 0x21, 0xf7, 0x03, 0x39, 0x14, 0x1d, 0x1f, 0xc5,
	0xd4, 0x54, 0x30, 0x9e, 0x20, 0x50, 0x0f, 0x9a, 0x87, 0xf1, 0x6c, 0x33, 0x9b, 0x51, 0xc6, 0xe4,
	0x74, 0x74, 0xdc, 0x48, 0x67, 0x4c, 0x15, 0x85, 0xbe, 0x04, 0x5d, 0xec, 0x5d, 0xb8, 0x51, 0xcb,
	0xc9, 0xa4, 0xc5, 0x3a, 0xae, 0xc6, 0xa0, 0x58, 0x42, 0xd6, 0xf9, 0x27, 0x0f, 0x30, 0x16, 0x4f,
	0xea, 0x65, 0x5f, 0xde, 0x41, 0x45, 0x4e, 0x6b, 0x2d, 0x16, 0x50, 0xb4, 0xba, 0x1f, 0x94, 0xdc,
	0x49, 0x0c, 0x77, 0xc9, 0x91, 0xa1, 0xb7, 0x50, 0x53, 0x2f, 0x74, 0xb7, 0xdb, 0xaa, 0x75, 0x5d,
	0xa2, 0x17, 0xc9, 0x82, 0xbb, 0xd0, 0x10, 0x32, 0xc8, 0x9a, 0x46, 0x64, 0x5f, 0xdc, 0x2c, 0xca,
	0xda, 0x6f, 0xba, 0x7b, 0x45, 0x5d, 0x21, 0xd3, 0xa5, 0xd1, 0xee, 0xd7, 0xe4, 0x06, 0x61, 0x83,
	0x3f, 0x82, 0xd1, 0x6f, 0x70, 0x1c, 0xd1, 0x80, 0x3c, 0x57, 0xb5, 0x24, 0xab, 0x7e, 0x95, 0xae,
	0x8a, 0x69, 0xf0, 0x7c, 0xe1, 0x46, 0xf4, 0x94, 0x11, 0x7b, 0x2e, 0x9e, 0x82, 0xfa, 0xea, 0x10,
	0x35, 0x64, 0xb3, 0x2c, 0xb7, 0x4e, 0xbd, 0x0b, 0x59, 0x14, 0xd7, 0x79, 0x72, 0xbc, 0x91, 0x21,
	0xa8, 0x07, 0xf5, 0x54, 0xde, 0xc7, 0x60, 0x43, 0x4d, 0xed, 0x49, 0x96, 0xbe, 0xcb, 0x3a, 0x0f,
	0x36, 0xb4, 0xd5, 0x87, 0xe6, 0xb3, 0xca, 0x90, 0x01, 0xb9, 0xdf, 0xe9, 0x36, 0x9e, 0x8c, 0x38,
	0x8a, 0xd5, 0xfc, 0xe4, 0x8b, 0xa2, 0xf1, 0xc2, 0xca, 0xcb, 0xcf, 0xd9, 0x1f, 0x33, 0xad, 0x01,
	0x98, 0x2f, 0x75, 0xf8, 0x7f, 0x75, 0xb2, 0xa9, 0x3a, 0x67, 0xbf, 0xaa, 0x37, 0x23, 0x9f, 0x3d,
	0x32, 0xa0, 0xea, 0xd9, 0xd6, 0x98, 0x5c, 0x3b, 0x57, 0xce, 0xe4, 0x83, 0x63, 0x7c, 0x86, 0xea,
	0x50, 0x91, 0xc8, 0x8d, 0x3d, 0x1a, 0x4d, 0x3e, 0x18, 0x19, 0xa4, 0x83, 0x26, 0x81, 0xf3, 0xd1,
	0xb5, 0x6d, 0x64, 0xcf, 0xfe, 0xce, 0x42, 0x25, 0xf5, 0x9d, 0x45, 0x0d, 0xa8, 0xf7, 0x27, 0xe3,
	0xb1, 0xe5, 0x5c, 0xa4, 0x8a, 0x18, 0x50, 0x4d, 0xc0, 0xf7, 0xd6, 0xc8, 0x33, 0x32, 0x69, 0x64,
	0xea, 0x4d, 0x5c, 0x23, 0x8b, 0x4c, 0x78, 0x95, 0x20, 0xce, 0x04, 0x8f, 0xad, 0x11, 0x99, 0x7a,
	0x16, 0xf6, 0x8c, 0x1c, 0x3a, 0x86, 0x46, 0xc2, 0x0c, 0x26, 0xb8, 0x6f, 0xc7, 0x44, 0x1e, 0xbd,
	0x86, 0xe3, 0x84, 0x70, 0xb1, 0xed, 0x5a, 0xd8, 0x26, 0x57, 0xc3, 0xfe, 0xd5, 0x64, 0x30, 0x30,
	0x0a, 0xcf, 0x91, 0xae, 0xed, 0x58, 0x23, 0xef, 0xc6, 0x28, 0xa6, 0x4b, 0x5e, 0x0c, 0xb1, 0xdd,
	0xf7, 0xc8, 0x00, 0xdb, 0xb6, 0x51, 0x42, 0x27, 0xd0, 0x4c, 0x88, 0xa1, 0x93, 0xa6, 0xca, 0xe9,
	0xce, 0xbc, 0xe1, 0xd8, 0x9e, 0x5c, 0x7b, 0x86, 0x86, 0x5a, 0xf0, 0x79, 0x02, 0x9e, 0x5b, 0xa3,
	0x11, 0x71, 0x47, 0x56, 0xdf, 0x1e, 0xdb, 0x8e, 0x67, 0xc0, 0xd9, 0x9f, 0x59, 0xd0, 0x0f, 0xbe,
	0xea, 0xe8, 0x08, 0x74, 0xf7, 0xbd, 0x35, 0xb5, 0x53, 0xd6, 0xd4, 0x00, 0x14, 0x14, 0x1b, 0xb3,
	0xbb, 0xc7, 0xb6, 0xec, 0x52, 0xf0, 0xb5, 0xe3, 0x0c, 0x9d, 0x4b, 0x23, 0xb7, 0x87, 0x12, 0x19,
	0x79, 0x31, 0x25, 0x05, 0x9d, 0x63, 0xdb, 0xba, 0x32, 0x0a, 0x42, 0xac, 0x02, 0xdc, 0xc9, 0xd4,
	0x23, 0x97, 0xd6, 0xd8, 0x36, 0x8a, 0xa2, 0xb9, 0x18, 0x7c, 0xe4, 0x56, 0xe9, 0x29, 0x95, 0x78,
	0x55, 0x46, 0x4d, 0x38, 0x52, 0x54, 0xda, 0x0e, 0x4d, 0x58, 0xa8, 0xe0, 0x43, 0x9f, 0x40, 0x0c,
	0x32, 0xd6, 0x72, 0x68, 0x48, 0xe5, 0x63, 0x51, 0xfe, 0x63, 0x7f, 0xf7, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x18, 0xf3, 0x4f, 0x9a, 0xe5, 0x07, 0x00, 0x00,
}
