// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: logs/ssl_log_index.proto

package logs

import (
	gc "github.com/RoboCup-SSL/ssl-go-tools/internal/gc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SslLogIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameEvents    []*GameEventIndex      `protobuf:"bytes,1,rep,name=game_events,json=gameEvents" json:"game_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SslLogIndex) Reset() {
	*x = SslLogIndex{}
	mi := &file_logs_ssl_log_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SslLogIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SslLogIndex) ProtoMessage() {}

func (x *SslLogIndex) ProtoReflect() protoreflect.Message {
	mi := &file_logs_ssl_log_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SslLogIndex.ProtoReflect.Descriptor instead.
func (*SslLogIndex) Descriptor() ([]byte, []int) {
	return file_logs_ssl_log_index_proto_rawDescGZIP(), []int{0}
}

func (x *SslLogIndex) GetGameEvents() []*GameEventIndex {
	if x != nil {
		return x.GameEvents
	}
	return nil
}

type GameEventIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *uint64                `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	GameEvent     *gc.GameEvent_Type     `protobuf:"varint,2,opt,name=game_event,json=gameEvent,enum=GameEvent_Type" json:"game_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEventIndex) Reset() {
	*x = GameEventIndex{}
	mi := &file_logs_ssl_log_index_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEventIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEventIndex) ProtoMessage() {}

func (x *GameEventIndex) ProtoReflect() protoreflect.Message {
	mi := &file_logs_ssl_log_index_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEventIndex.ProtoReflect.Descriptor instead.
func (*GameEventIndex) Descriptor() ([]byte, []int) {
	return file_logs_ssl_log_index_proto_rawDescGZIP(), []int{1}
}

func (x *GameEventIndex) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *GameEventIndex) GetGameEvent() gc.GameEvent_Type {
	if x != nil && x.GameEvent != nil {
		return *x.GameEvent
	}
	return gc.GameEvent_Type(0)
}

var File_logs_ssl_log_index_proto protoreflect.FileDescriptor

const file_logs_ssl_log_index_proto_rawDesc = "" +
	"\n" +
	"\x18logs/ssl_log_index.proto\x1a\x1agc/ssl_gc_game_event.proto\"?\n" +
	"\vSslLogIndex\x120\n" +
	"\vgame_events\x18\x01 \x03(\v2\x0f.GameEventIndexR\n" +
	"gameEvents\"^\n" +
	"\x0eGameEventIndex\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12.\n" +
	"\n" +
	"game_event\x18\x02 \x01(\x0e2\x0f.GameEvent.TypeR\tgameEventBGB\x10SslLogIndexProtoP\x01Z1github.com/RoboCup-SSL/ssl-go-tools/internal/logs"

var (
	file_logs_ssl_log_index_proto_rawDescOnce sync.Once
	file_logs_ssl_log_index_proto_rawDescData []byte
)

func file_logs_ssl_log_index_proto_rawDescGZIP() []byte {
	file_logs_ssl_log_index_proto_rawDescOnce.Do(func() {
		file_logs_ssl_log_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logs_ssl_log_index_proto_rawDesc), len(file_logs_ssl_log_index_proto_rawDesc)))
	})
	return file_logs_ssl_log_index_proto_rawDescData
}

var file_logs_ssl_log_index_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_logs_ssl_log_index_proto_goTypes = []any{
	(*SslLogIndex)(nil),    // 0: SslLogIndex
	(*GameEventIndex)(nil), // 1: GameEventIndex
	(gc.GameEvent_Type)(0), // 2: GameEvent.Type
}
var file_logs_ssl_log_index_proto_depIdxs = []int32{
	1, // 0: SslLogIndex.game_events:type_name -> GameEventIndex
	2, // 1: GameEventIndex.game_event:type_name -> GameEvent.Type
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_logs_ssl_log_index_proto_init() }
func file_logs_ssl_log_index_proto_init() {
	if File_logs_ssl_log_index_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logs_ssl_log_index_proto_rawDesc), len(file_logs_ssl_log_index_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_logs_ssl_log_index_proto_goTypes,
		DependencyIndexes: file_logs_ssl_log_index_proto_depIdxs,
		MessageInfos:      file_logs_ssl_log_index_proto_msgTypes,
	}.Build()
	File_logs_ssl_log_index_proto = out.File
	file_logs_ssl_log_index_proto_goTypes = nil
	file_logs_ssl_log_index_proto_depIdxs = nil
}
