version: 2
jobs:
  tools:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v -covermode=count -coverprofile=count.out ./...
      - run: go tool cover -html=count.out -o coverage.html
      - store_artifacts:
          path: coverage.html
          destination: coverage

  docker-auto-recorder:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run: |
          # remove 'ssl-auto-recorder/v'
          TAG=${CIRCLE_TAG:19}
          TAG=${TAG:-latest}
          docker build -f ssl-auto-recorder.Dockerfile -t robocupssl/ssl-auto-recorder:$TAG .
          docker login -u "${DOCKER_HUB_USERNAME}" -p "${DOCKER_HUB_PASSWORD}"
          docker push robocupssl/ssl-auto-recorder:$TAG

  docker-log-player:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run: |
          # remove 'ssl-log-player/v'
          TAG=${CIRCLE_TAG:16}
          TAG=${TAG:-latest}
          docker build -f ssl-log-player.Dockerfile -t robocupssl/ssl-log-player:$TAG .
          docker login -u "${DOCKER_HUB_USERNAME}" -p "${DOCKER_HUB_PASSWORD}"
          docker push robocupssl/ssl-log-player:$TAG

  release:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: curl -sfL https://goreleaser.com/static/run | bash

workflows:
  version: 2
  main:
    jobs:
      - tools:
          filters:
            tags:
              only: /.*/
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - docker-auto-recorder:
          context: docker hub
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^ssl-auto-recorder\/v.*/
      - docker-log-player:
          context: docker hub
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^ssl-log-player\/v.*/
