// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gc/ssl_gc_geometry.proto

package gc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A vector with two dimensions
type Vector2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *float32               `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y             *float32               `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector2) Reset() {
	*x = Vector2{}
	mi := &file_gc_ssl_gc_geometry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2) ProtoMessage() {}

func (x *Vector2) ProtoReflect() protoreflect.Message {
	mi := &file_gc_ssl_gc_geometry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2.ProtoReflect.Descriptor instead.
func (*Vector2) Descriptor() ([]byte, []int) {
	return file_gc_ssl_gc_geometry_proto_rawDescGZIP(), []int{0}
}

func (x *Vector2) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Vector2) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

// A vector with three dimensions
type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *float32               `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y             *float32               `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	Z             *float32               `protobuf:"fixed32,3,req,name=z" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_gc_ssl_gc_geometry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_gc_ssl_gc_geometry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_gc_ssl_gc_geometry_proto_rawDescGZIP(), []int{1}
}

func (x *Vector3) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Vector3) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

var File_gc_ssl_gc_geometry_proto protoreflect.FileDescriptor

const file_gc_ssl_gc_geometry_proto_rawDesc = "" +
	"\n" +
	"\x18gc/ssl_gc_geometry.proto\"%\n" +
	"\aVector2\x12\f\n" +
	"\x01x\x18\x01 \x02(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x02(\x02R\x01y\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x02(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x02(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x02(\x02R\x01zBGB\x12SslGcGeometryProtoP\x01Z/github.com/RoboCup-SSL/ssl-go-tools/internal/gc"

var (
	file_gc_ssl_gc_geometry_proto_rawDescOnce sync.Once
	file_gc_ssl_gc_geometry_proto_rawDescData []byte
)

func file_gc_ssl_gc_geometry_proto_rawDescGZIP() []byte {
	file_gc_ssl_gc_geometry_proto_rawDescOnce.Do(func() {
		file_gc_ssl_gc_geometry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gc_ssl_gc_geometry_proto_rawDesc), len(file_gc_ssl_gc_geometry_proto_rawDesc)))
	})
	return file_gc_ssl_gc_geometry_proto_rawDescData
}

var file_gc_ssl_gc_geometry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gc_ssl_gc_geometry_proto_goTypes = []any{
	(*Vector2)(nil), // 0: Vector2
	(*Vector3)(nil), // 1: Vector3
}
var file_gc_ssl_gc_geometry_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gc_ssl_gc_geometry_proto_init() }
func file_gc_ssl_gc_geometry_proto_init() {
	if File_gc_ssl_gc_geometry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gc_ssl_gc_geometry_proto_rawDesc), len(file_gc_ssl_gc_geometry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gc_ssl_gc_geometry_proto_goTypes,
		DependencyIndexes: file_gc_ssl_gc_geometry_proto_depIdxs,
		MessageInfos:      file_gc_ssl_gc_geometry_proto_msgTypes,
	}.Build()
	File_gc_ssl_gc_geometry_proto = out.File
	file_gc_ssl_gc_geometry_proto_goTypes = nil
	file_gc_ssl_gc_geometry_proto_depIdxs = nil
}
